### ISSUE TITLE
SIGHUP / fs-reload not working

### ISSUE THREAD

**Issue by rattrayalex** [unbit/uwsgi-docs#189]
graceful reloads don't seem to be working consistently for me. I tried running uwsgi with the `fs-reload` option, which seemed to work for a while. Then I tried the following code in another process:
```python
for process in psutil.get_process_list():
  if process.name() in ['python', 'uwsgi']:
    os.kill(process.pid, signal.SIGHUP)
```

Unfortunately, only one or two of my 4 threads seem to have reloaded. 

There were no ongoing requests at time of requested reload. There were many requests afterwards. Only some of them returned the updated response.

**Comment by xrmx** [comment]
Closing then, please open an uwsgi issue if it's still an issue and it's not already been reported. Thanks!

**Comment by rattrayalex** [comment]
Actually, the resolution of that issue was that the docs should be updated to recommend touch-reload over fs-reload, and explain why the latter is less reliable. And perhaps also to describe the advantages of a matter fifo / pidfile, though that was probably secondary.

**Comment by xrmx** [comment]
@rattrayalex sure and i've kept the one with more context. Thanks.

**Comment by rattrayalex** [comment]
Great! Thanks =)
