### ISSUE TITLE
How to setup a Unix file socket?

### ISSUE THREAD

**Issue by Swashy** [unbit/uwsgi-docs#221]
The django and and nginx tutorial does not explain how to make a socket for nginx to talk to django, it is just assumed that the .sock file already exists.

**Comment by akx** [comment]
uWSGI will create the socket file, you don't have to worry about it.

(And unless you use `--vacuum`, it won't be deleted automatically either.)

```sh
$ mkdir sock_drawer
[akx@xar uwsgi-2.0.6]$ ./uwsgi --socket sock_drawer/red.sock
*** Starting uWSGI 2.0.6 (64bit) on [Mon Feb 23 20:47:12 2015] ***
[...]
uwsgi socket 0 bound to UNIX address sock_drawer/red.sock fd 3
[...]
spawned uWSGI worker 1 (and the only) (pid: 1664, cores: 1)
^C
[akx@xar uwsgi-2.0.6]$ ls sock_drawer/
red.sock
[akx@xar uwsgi-2.0.6]$
```
