### ISSUE TITLE
Django tutorial : suggested /etc/rc.local conf breaks things

### ISSUE THREAD

**Issue by michelbl** [unbit/uwsgi-docs#233]
In https://github.com/unbit/uwsgi-docs/blob/master/tutorials/Django_and_nginx.rst, paragraph "Make uWSGI startup when the system boots", it is suggested to add the line 
"/usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --uid www-data --gid www-data"
to /etc/rc.local. However this command never returns and every init script coming after /etc/init.d/rc.local is never executed. I suggest to add 
"/usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --uid www-data --gid www-data &"
instead.

**Comment by akx** [comment]
Or `--daemonize /var/log/uwsgi-emperor.log` to actually capture logs too :)

**Comment by michelbl** [comment]
That's much better indeed !

**Comment by xrmx** [comment]
@michelbl , @akx  care to cook a patch?

**Comment by akx** [comment]
Cooked & submitted!
