### ISSUE TITLE
Https issue

### ISSUE THREAD

**Issue by zichuanxiu06** [unbit/uwsgi-docs#236]
I am using  nginx+django+uwsgi to deploy my app.
Now I get a strange error with https  issue
My django version is 1.6, uwsgi version is 2.0.4 and python version is 2.7.3
I can visit https url by django shell:
In [1]: import urllib2
In [2]: response=urllib2.urlopen("https://www.baidu.com")
In [3]: data=resposne.read()
In [5]: print data
<html>
<head>
        <script>
                location.replace(location.href.replace("https://","http://"));
        </script>
</head>
<body>
        <noscript><meta http-equiv="refresh" content="0;url=http://www.baidu.com/"></noscript>
</body>
</html>
But if I start my app with uwsgi, I get an error :urlopen error unknown url type: https with same code
I dont know why, can you guys help me?

**Comment by unbit** [comment]
which error ?

**Comment by zichuanxiu06** [comment]
<urlopen error unknown url type: https>

**Comment by zichuanxiu06** [comment]
urlopen error unknown url type: https

**Comment by unbit** [comment]
You uwsgi instance is using a python version compiled without ssl support. Very probably you have more than one python version in the system

**Comment by zichuanxiu06** [comment]
How can I fix it if it is true
recompile python ?  recompile uwsgi?

**Comment by unbit** [comment]
you need to recompile the python used by uwsgi (and eventually uwsgi too if it is using a static library)

**Comment by zichuanxiu06** [comment]
any other solutions?
recompile python is unaccepted now because it is risky for us

**Comment by unbit** [comment]
then remove that python version as you already have one working in the system

**Comment by zichuanxiu06** [comment]
I tried to find another python, and i make it
but i tried the same code with another python like:
./python2.6
In [1]: import urllib2
In [2]: response=urllib2.urlopen("https://www.baidu.com")
In [3]: data=resposne.read()
In [4]: print data
Still it works fine

**Comment by unbit** [comment]
just get the python version used by the uwsgi binary, and remove that one. On linux you can use ldd (if you do not see libpython in the list your uwsgi has been built with a static python library without ssl, and so you need to rebuild using one of the correct python versions in your system)

**Comment by zichuanxiu06** [comment]
with uwsgi, full stack of the issue,
Traceback (most recent call last):
  File "/usr/local/app/python-2.7.3/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./tesly/wechat/core/views.py", line 27, in bind_qq
    open_id=get_openId_by_code(code)
  File "./tesly/wechat/core/helper.py", line 61, in get_openId_by_code
    data=send_get(CODE_URL)
  File "./tesly/wechat/utils/httputils.py", line 51, in send_get
    r=urllib2.urlopen("https://wwww.baidu.com")
  File "/usr/local/app/python-2.7.3/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/app/python-2.7.3/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/local/app/python-2.7.3/lib/python2.7/urllib2.py", line 423, in _open
    'unknown_open', req)
  File "/usr/local/app/python-2.7.3/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/local/app/python-2.7.3/lib/python2.7/urllib2.py", line 1240, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: https>
It is using python 2.7.3

**Comment by zichuanxiu06** [comment]
thanks   very much
I'll try your solution

**Comment by zichuanxiu06** [comment]
problem solved.
thanks
