### ISSUE TITLE
missing --wsgi-env-behaviour documentation

### ISSUE THREAD

**Issue by xrmx** [unbit/uwsgi-docs#267]
From 1.2.4 changelog:

```
* added --wsgi-env-behaviour for choosing the WSGI environ
allocator/destroyer policy

There are two policies available:

'cheat' (the default one) it preallocates the env dictionary on uWSGI
startup and clear it after each request

'holy' it creates and destroyes the environ dictionary at each request
```

**Comment by adamchainz** [comment]
Please add, I googled for the docs and found only this plus the [rather empty listing under 'Options'](https://uwsgi-docs.readthedocs.io/en/latest/Options.html?highlight=wsgi-env-behaviour#wsgi-env-behaviour) after being linked to #1408 to fix my New Relic installation.
