### ISSUE TITLE
Suggest using safe-pidfile instead of pidfile

### ISSUE THREAD

**Issue by federicobond** [unbit/uwsgi-docs#281]
There is no documentation around the `safe-pidfile` option except [this pull request](https://github.com/unbit/uwsgi/pull/800) but it looks like a better alternative to the standard `pidfile` option and I think it should be recommended for all new projects.

I can submit a pull request updating the docs if you are OK with this.

**Comment by xrmx** [comment]
@federicobond sure, please open a pull request
