### ISSUE TITLE
Missing wheel for uwsgi package

### ISSUE THREAD

**Issue by eddwardo** [unbit/uwsgi-docs#296]
In order to install uwsgi user need all kind of build tools to do that. It would make sense to ship a wheel (binary format with pre compiled libs for each distribution ie. linux, mac os, windows) to save a lot users time.

Are there any plans to do it?

**Comment by akx** [comment]
I don't think it's feasible to build wheels for Linux that would reliably work with every distribution/package version/ABI.

In addition, the wheels built would probably be Python-only, targeting the particular Python version the wheel is for.  This would undermine using `UWSGI_PROFILE=foo pip install uwsgi` to build another configuration (unless one used something like `--no-wheel`).

OSX wheels don't need to care that much about the distro/ABI thing, but the Python-only proviso still holds.

And, tbh, on an Ubuntu/Debian box, you really only need one `sudo apt-get install python python-dev build-essential` to be able to build uWSGI -- I'd hardly call that "all kind of build tools".

**Comment by xrmx** [comment]
@eddwardo what about using binaries shipped by your distribution?

**Comment by xrmx** [comment]
@eddwardo btw this is the wrong repo to discuss uwsgi packaging :)

**Comment by eddwardo** [comment]
Thanks for the reply
