### ISSUE TITLE
uwsgi: unrecognized option `--zeromq'

### ISSUE THREAD

**Issue by ajbeach2** [unbit/uwsgi-docs#298]
per the docs on attaching uwsgi to mongrel,  zeromq is not a valid  option. I am using v 2.0.12  of uwsqi                                                                                                                                                      

uwsgi --zeromq
Wed Mar 16 14:46:49 CDT 2016
uwsgi: unrecognized option `--zeromq'
getopt_long() error

**Comment by xrmx** [comment]
Have you built and loaded the mongrel2 plugin?

**Comment by ajbeach2** [comment]
Hmm no I am using the brew

**Comment by xrmx** [comment]
You haven't answered my question though. If you are not building and loading the plugin then there's no way to have it work. Closing.
