### ISSUE TITLE
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]

### ISSUE THREAD

**Issue by tmacjx** [unbit/uwsgi-docs#323]
I used an virtualenv, uwsgi and nginx to deploy an Django project.
when I run the command of 'uwsgi --ini uwsgi.ini' to set up the project.
I found some error showed in the content of uwsgi.log.
Show below:
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]
Can't anyone help?Maybe Permission Problem?
Thanks a lot.

**Comment by tmacjx** [comment]
Full info show below.

*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Aug 26 11:20:43 2016] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-4) on 19 August 2016 14:24:34
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: iZ230ph83b2Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /alidata/websites/LandsBLog
detected binary path: /root/.virtualenvs/blog/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /alidata/websites/LandsBLog/LandsBlog
your processes number limit is 7283
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8077 fd 3
Python version: 3.4.1 (default, Aug 19 2016, 10:38:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Set PythonHome to /root/.virtualenvs/blog
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ddfa90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507200 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ddfa90 pid: 6583 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6583)
spawned uWSGI worker 1 (pid: 6585, cores: 1)
spawned uWSGI worker 2 (pid: 6586, cores: 1)
spawned uWSGI worker 3 (pid: 6587, cores: 1)
spawned uWSGI worker 4 (pid: 6588, cores: 1)
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]
[pid: 6585|app: 0|req: 1/1] 123.59.134.177 () {38 vars in 581 bytes} [Fri Aug 26 12:29:26 2016] GET /http/detect => generated 3816 bytes in 33 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 6585|app: 0|req: 2/2] 60.191.52.254 () {32 vars in 421 bytes} [Fri Aug 26 13:12:40 2016] HEAD / => generated 0 bytes in 94 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)

**Comment by xrmx** [comment]
Wrong repository :) also without configuration quite difficult to help you. Please reopen with the needed information on https://github.com/unbit/uwsgi
