### ISSUE TITLE
eager for Chinese version

### ISSUE THREAD

**Issue by ictar** [unbit/uwsgi-docs#328]
If there is anyone like me expecting a Chinese version for this docs?
English version is good, but if there is a Chinese version in hand for us Chinese persons, it would be awesome. And that will be very convenient for further use.

**Comment by xrmx** [comment]
We have trouble keeping up to date the english version, chances to have an up to date chinese version are pretty slim. Said that any translation is appreciated. We'll have to sort out how this should be handled with sphinx / read the docs.
