### ISSUE TITLE
projects.unbit.it certificate expired

### ISSUE THREAD

**Issue by tylrtrmbl** [unbit/uwsgi-docs#345]
⚠️ Security problem

It looks like my pull request from August (#321) and @jdufresne's from just a few days ago (#344) have come back to haunt us! I'm currently seeing the TLS cert for `*.unbit.it` that's currently in use for `projects.unbit.it` has expired.

Precise URL tested: https://projects.unbit.it/downloads/uwsgi-2.0.13.1.tar.gz

I also get the following warning from Chrome, for what it's worth:
> The connection to this site uses an obsolete protocol (TLS 1.0), an obsolete key exchange (RSA), and an obsolete cipher (AES_128_CBC with HMAC-SHA1).

I'd recommend upgrading your TLS configuration to match the "Intermediate" TLS config [recommended by Mozilla](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29). Not too new to baffle automated tooling, not so old it needlessly supports things like IE 6.

cc/ @xrmx

**Comment by unbit** [comment]
Problem should be fixed now. Thanks a lot.
