### ISSUE TITLE
documentation still mentions --http flag

### ISSUE THREAD

**Issue by rgardam** [unbit/uwsgi-docs#359]
I don't believe this is in the latest version of uwsgi and should be removed or the documentation should be versioned.

**Comment by unbit** [comment]
yes, --http is part of the standard distribution. In 8 years we removed only 5 options :)

**Comment by xrmx** [comment]
Il 20/06/2017 15:41, unbit ha scritto:
> yes, --http is part of the standard distribution. In 8 years we removed only 5 
> options :)

That should have been a sad face though ;)

**Comment by xrmx** [comment]
Also closing. You are possibly not seeing --http because you haven't loaded the http plugin.

**Comment by rgardam** [comment]
Yeah, I was using the centos package of uwsgi from epel. it's not included there.
