### ISSUE TITLE
Protocol documentation lacks details on packet size limits

### ISSUE THREAD

**Issue by artyom** [unbit/uwsgi-docs#376]
[The protocol description](https://github.com/unbit/uwsgi-docs/blob/master/Protocol.rst#packet-descriptions) states that request packet body size is specified in the 4-byte header as uint16 (packet with modifier1==0), thus limiting single packet size to 64k.

From the protocol description itself it seems that the only way of sending request packet bigger than 64k (i.e. request with large headers) is to use modifier1==30, which allows using 24 bits to specify packet size, allowing 16Mb packets. But this type of request packets has documented side effect (modification of `PATH_INFO`) and is (somewhere) mentioned as deprecated.

From sniffing traffic between nginx and uwsgi it seems that nginx only uses request packets with modifier1==0 (size specified as uint16) and just lets size value overflow and uwsgi somehow transparently deals with it.

I wish this behavior was documented better — I'm trying to communicate with uWSGI backend and it's not clear how these limits should properly be handled.

**Comment by unbit** [comment]
Hi, the uwsgi protocol only supports up to 64k header/dictionary values. For bigger values you need to use http or fastcgi. Attempts to move it to 24bit required to remove optimizations that makes the uwsgi protocol advantages basically irrelevant over http or fastcgi.

**Comment by artyom** [comment]
Thank you for reply; so the max *total size of all request headers* is limited to 64k, is that correct?

**Comment by unbit** [comment]
yep
