### ISSUE TITLE
OpenBSD Posix Semaphores

### ISSUE THREAD

**Issue by raratiru** [unbit/uwsgi-docs#403]
I intend to build an OpenBSD web server and I read in [the docs](http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html) that:

> On OpenBSD, NetBSD and FreeBSD < 9, SysV IPC semaphores are used as the locking subsystem. These operating systems tend to limit the number of allocable semaphores to fairly small values. You should raise the default limits if you plan to run more than one uWSGI instance. FreeBSD 9 has POSIX semaphores, so you do not need to bother with that.

However, the default PostgreSQL setting is `dynamic_shared_memory_type = posix`. 

```
ipcs -s
Semaphores:
T       ID     KEY        MODE       OWNER    GROUP
s  1310720    5432001 --rw------- _postgresql _postgresql
s  1310721    5432002 --rw------- _postgresql _postgresql
s  1310722    5432003 --rw------- _postgresql _postgresql

```

When I run the [The first WSGI application](http://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#the-first-wsgi-application), uWSGI is appended to the above table.

I also see that there is a [sem_init()](https://man.openbsd.org/sem_init.3) man page.

Should I configure the relevant `System V IPC` limits, nonetheless?

**Comment by unbit** [comment]
Hi, yes you should increase them or you could get problems when spawning more instances or using specific features (like caching)

**Comment by raratiru** [comment]
Thank you!

**Comment by raratiru** [comment]
Postgresql, uses [approximately](https://www.postgresql.org/docs/current/static/kernel-resources.html#SYSVIPC-PARAMETERS) one semaphore per connection and the docs give a hint on how to set the relevant configuration elements.

How can I calculate the relevant numbers for uwsgi? OK, I can inflate the sql config parameters and get somehow a result, but I am trying to learn at the same time how to tune my server and I would like to be able to justify the changes I make.

**Comment by raratiru** [comment]
OK, besides the [memory_report](http://uwsgi-docs.readthedocs.io/en/latest/Options.html#memory-report) and [uwsgitop](https://github.com/xrmx/uwsgitop), the command `ipcs -b`, along with [this issue](https://github.com/unbit/uwsgi/issues/1508) helped a lot finding out what to configure and why!
