### ISSUE TITLE
"uWSGI process got Segmentation Fault" after disconnect and reconnect network

### ISSUE THREAD

**Issue by liuguichao** [unbit/uwsgi-docs#412]
I deploy a flask app with nginx(1.10.3)+uwsgi(2.0.17) on Ubuntu 16.04.

    [uwsgi]
    module = app:app
    master = true
    processes = 4
    chdir = /usr/local/reportapi
    socket = /opt/reportapi/reportapi.sock
    chmod-socket = 666
    vacuum = true
    buffer-size = 65535
    die-on-term = true
    logto = /opt/reportapi/log/uwsgi.log

after start the services, disconnect the network and reconnect after a few seconds.

    sudo ifconfig ens160 down
    sudo ifconfig ens160 up

 the uwsgi log shows: 

    [pid: 13264|app: 0|req: 12/50] 10.103.238.60 () {50 vars in 798 bytes} [Thu Jun 21 11:15:59 2018] GET /api/samples/1eb007b603bffd54c3f332fa23f92e95b97ab425f4543b27b190c0edfe90e836 => generated 470 bytes in 32 msecs (HTTP/1.1 200) 2 headers in 72 bytes (2 switches on core 0)
    !!! uWSGI process 13266 got Segmentation Fault !!!
    !!! uWSGI process 13264 got Segmentation Fault !!!
    !!! uWSGI process 13265 got Segmentation Fault !!!
    !!! uWSGI process 13267 got Segmentation Fault !!!

**I have tested the same case under Ubuntu 14.04, it works fine after reconnect network.**

I want to known how to config the uwsgi server, let it recovery automatically from this situation.

**Comment by xrmx** [comment]
That's the repository of the documentation
