### ISSUE TITLE
Uwsgi not locating python3.6!!

### ISSUE THREAD

**Issue by sindhujit** [unbit/uwsgi-docs#434]
I am having this issue for a long time. I have my automation tool for my company working on python2.7 + nginx + uwsgi. However, due to the python countdown, we wanted to upgrade python2 to python3. After creating everyting with python3, uwsgi cannot locate python3.6. Getting the error :
--- no python application found, check your startup logs for errors ---
in the logs.
When I try to build the python plugin for uwsgi , we get :-
(netadc1) [netadc@hqiqlavxwa05 netadc1]$ PYTHON=python3.6 /home/netadc/.venvs2/netadc1/bin/uwsgi --build-plugin "/home/netadc/requirements/common/uwsgi-2.0.13.1/plugins/python python36"
*** uWSGI building and linking plugin from /home/netadc/requirements/common/uwsgi-2.0.13.1/plugins/python ***
[gcc -pthread] python36_plugin.so
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
*** unable to build python36 plugin ***

If I just install uwsgi through pip3.6 without building uwsgi, I get the no python application found error. Is it necessary to build uwsgi with python plugin!?
Any help is appreciated!!

**Comment by xrmx** [comment]
The linker errors suggestes to use a proper built python3 and not the one you are using.

**Comment by sindhujit** [comment]
I am using python3.6.7 and it installed properly

**Comment by sindhujit** [comment]
Please try to provide proper solution, instead of giving generic comments. I have tried all possible means to get this working till this point. Do not close it unless the issue owner gives his consent for the same.
