### ISSUE TITLE
Getting Command 'uwsgi' not found error even after installing.

### ISSUE THREAD

**Issue by Padmahas** [unbit/uwsgi-docs#448]
Hello,

I have installed "uwsgi" using pip method. But when I run uwsgi, I'm getting "Command 'uwsgi' not found, but can be installed with" error.
If I again try to install using pip, I'm getting

> Collecting uwsgi
> Installing collected packages: uwsgi
> Successfully installed uwsgi-2.0.18

which means it's already been installed.

What else am I missing out here.
Thank you.

**Comment by kant-li** [comment]
Usually it's because the uwsgi is installed in another python environment, keep a mind on the difference of pip and pip3 command, or the virtual environment you are in.
