### ISSUE TITLE
Is there documentation on the %variables that can be used in a uwsgi.ini file?

### ISSUE THREAD

**Issue by jonfen** [unbit/uwsgi-docs#453]
This is a dump from a python flask project, where can I go to figure out what some of these mean?

%b /usr/local/bin/uwsgi
%c app
%d /app/
%e ini 
%g 0
%h 700d1e531733
%i 44961763
%j 5B7C1944
%k 8
%n uwsgi 
%p /app/uwsgi.ini
%s uwsgi.ini
%t 1567534011
%u 0
%v /app
%x default

**Comment by xrmx** [comment]
What about looking in the documentation before opening an issue?
https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#magic-variables

**Comment by jonfen** [comment]
I did try to search, but I didn't guess the "magic" search word.  I greatly appreciate the link.

"If the user has a bad time, it's a bug."
