### ISSUE TITLE
OverflowError: long int too large to convert to int

### ISSUE THREAD

**Issue by sunshine69** [unbit/uwsgi-docs#69]
I just tried today - compiled fine, startup fine. However when I run (a django app) and make a request via browser, I got internal server error. 

Searching the log of uwsgi I found this:

From callback <function uwsgi_pypy_wsgi_handler at 0xb406cf10>:
Traceback (most recent call last):
  File "c callback", line 235, in uwsgi_pypy_wsgi_handler
  File "/opt/pypy-2.0.2/lib_pypy/cffi/api.py", line 226, in string
    return self._backend.string(cdata, maxlen)
OverflowError: long int too large to convert to int

This is on ubuntu 10.04 i686. The libpypy-c is built locally to match up with libssh version and libffi etc..

if you need more action in order to debug please let me know

**Comment by xrmx** [comment]
2 years without answer and wrong bug tracker, closing.
