### ISSUE TITLE
uWsgi random spikes to 100%

### ISSUE THREAD

**Issue by joshspivey** [unbit/uwsgi-docs#79]
uWsgi is randomly spiking to 100% for a few seconds on a nginx/Django/Python project. Has anyone seen this issue before? Another developer is saying that its because dJango doesn't know how to serve dynamic generated JavaScript files I don't believe that's the case at all. How would one go about debugging this issue?

**Comment by xrmx** [comment]
2 years without answer and wrong bug tracker, closing.
